### ISSUE TITLE
Please invite me to the Keymeta Networks

### ISSUE THREAD

**Issue by izam-mohammed** [Keymeta-Networks/comunity#2]
### Name

Izam Mohammed

### E-mail address

izamdeveloper1@gmail.com

### Additional Context

I would love to join the community to learn and contribute more.

**Comment by DevKob** [comment]
Approved!
Welcome to the Keymeta Network.
We hope you can contribute to this community. 
Thank You

**Comment by izam-mohammed** [comment]
Thanks for the approval

**Comment by izam-mohammed** [comment]
Please give an invitation to the organization.

**Comment by DevKob** [comment]
I've sent an invite by email. Please confirm

**Comment by izam-mohammed** [comment]
I am sorry, it expired @samkoba, Would you send that once more if possible?

**Comment by DevKob** [comment]
Sure, please check again your email @izam-mohammed
